# Generated by Django 5.1.3 on 2024-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Направлена в работу', 'Направлена в работу'), ('Выполнена', 'Выполнена')], default='pending', max_length=20),
        ),
    ]
